title: "Semerkand Blog"
name: "Semerkand"
email: metinzorlu@msn.com
description: Kişisel Blog Sayfası 

baseurl: "/semerkand" 
url: "" 
paginate: 2

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
