title: "Semerkand Blog"
name: "Semerkand"
email: metinzorlu@msn.com
description: Kişisel Blog Sayfası. 

baseurl: "/semerkand" 
url: "" 
paginate: 2

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: coderay
  syntax_highlighter_opts:
    line_numbers: table
    bold_every: 5


plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
