# Welcome to Jekyll!

title: "Semerkand Blog"
name: "Semerkand"
email: metinzorlu@msn.com
description: Kişisel Blog Sayfası. 

baseurl: "/semerkand" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com 
twitter_username: deruni
github_username: mtnzorlu

paginate: 2

plugins:
  - jekyll-feed
  - jekyll-paginate
